apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xnamespaces.altimetrik.com
spec:
  group: altimetrik.com
  names:
    kind: XNamespace  # kubectl get xnamespaces
    plural: xnamespaces
  claimNames:
    kind: NamespaceClaim
    plural: namespaceclaims
  versions:
    - name: v1
      referenceable: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespaceName:
                  type: string
                  description: The name of the Kubernetes namespace to create
                labels:
                  type: object
                  additionalProperties:
                    type: string
                  description: Labels to apply to the namespace
              required:
              - namespaceName

# kubectl api-resources | grep altimetrik
