---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: github-crossplane-provider-testing
spec:
  forProvider:
    name: github-crossplane-provider-testing
    visibility: public
    autoInit: true
    gitignoreTemplate: Terraform
  providerConfigRef:
    name: dgeorgievski-github
