apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-examples
  namespace: argocd
spec:
  project: refspec
  source:
    repoURL: >-
      https://github.com/dgeorgievski/crossplane-examples.git
    path: providers/github/manifests/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
