apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-upjet-github
spec:
  package: crossplane-contrib/provider-upjet-github:v0.18.0

---

apiVersion: v1
kind: Secret
metadata:
  name: provider-secret
  namespace: upbound-system
type: Opaque
stringData:
  credentials: "{\"token\":\"${GH_TOKEN}\",\"owner\":\"${GH_OWNER}\"}"

# ---

# apiVersion: github.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: dgeorgievski-github
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       name: provider-secret
#       namespace: upbound-system
#       key: credentials
