apiVersion: v1
kind: Secret
metadata:
  name: crossplane-examples
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/dgeorgievski/crossplane-examples
