
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: github-crossplane-provider-testing
spec:
  forProvider:
    name: github-crossplane-provider-testing
    visibility: public
    gitignoreTemplate: Terraform
    autoInit: true
    squashMergeCommitTitle: PR_TITLE
    template:
      - owner: dgeorgievski 
        repository: hello 
        includeAllBranches: false 
    topics:
      - go
  providerConfigRef:
    name: dgeorgievski-github
